#!/bin/bash
DIR=$(dirname "$0")
mpc clear
mpc add 'Britland City Theme.mp3'
mpc volume 50
mpc repeat on
mpc single on
mpc play

od -t d2 --width=4 /tmp/my_fifo.fifo |
cut --delimiter ' ' --fields 2- |
python "$DIR/spectrum.py" |
python "$DIR/visualization.py" &

(sleep 1 && wmctrl -x -r tk -b add,fullscreen) &
